### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by erfelipe** [luigi-asprino/Graffoo4DrawIO#1]
Hi Luigi,
I'm try to import the lib with desktop and web version of draw.io, but isn't work. 

Can you try it?

Regards,

**Comment by luigi-asprino** [comment]
Hi.

I've just reimported the library and it seems to work fine.
Can you please tell me what kind of error you get?

Luigi

**Comment by erfelipe** [comment]
Of course.
In desktop (OS X version), there Is no objects in the palette:
![image](https://user-images.githubusercontent.com/17271754/79152400-818e9300-7da2-11ea-87d1-0132031f71dd.png)

In web version (safari browser):
![image](https://user-images.githubusercontent.com/17271754/79152473-a97df680-7da2-11ea-9085-ae63c22b8f50.png)

the same behavior. 

Do you want another test in my set? Try to import it again?

**Comment by luigi-asprino** [comment]
What version draw.io version do you have?
I've just installed the 12.9.9 (OS X) and I was able to correctly import the library.
It is slightly different from the online version so I've updated the installation instructions. 
By the way, I've also tried from Safari with the same result.

**Comment by erfelipe** [comment]
So, the desktop version is the same (latest 12.9.9).
I'm try the new installation instructions and with git clone, works. 

![image](https://user-images.githubusercontent.com/17271754/79224397-628b1200-7e31-11ea-9771-de05009fe433.png)

Thanks for your attention,
Regards,
